# Generated by Django 3.1.6 on 2021-02-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210216_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(null=True),
        ),
    ]
